# Generated by Django 2.1.2 on 2019-02-19 02:11

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('src_id', models.CharField(max_length=24)),
                ('ccodes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None)),
                ('dataset', models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='places', to='datasets.Dataset', to_field='label')),
            ],
            options={
                'db_table': 'places',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceDepiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('src_id', models.CharField(default='', max_length=24)),
                ('place_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='depictions', to='places.Place')),
            ],
            options={
                'db_table': 'place_depiction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('src_id', models.CharField(default='', max_length=24)),
                ('place_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='places.Place')),
            ],
            options={
                'db_table': 'place_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceGeom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('src_id', models.CharField(default='', max_length=24)),
            ],
            options={
                'db_table': 'place_geom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('review_note', models.CharField(blank=True, max_length=2044, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('src_id', models.CharField(default='', max_length=24)),
                ('place_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='places.Place')),
            ],
            options={
                'db_table': 'place_link',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('toponym', models.CharField(max_length=200)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('src_id', models.CharField(default='', max_length=24)),
            ],
            options={
                'db_table': 'place_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('src_id', models.CharField(default='', max_length=24)),
                ('place_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='places.Place')),
            ],
            options={
                'db_table': 'place_related',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('src_id', models.CharField(default='', max_length=24)),
                ('place_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='places.Place')),
            ],
            options={
                'db_table': 'place_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceWhen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('src_id', models.CharField(default='', max_length=24)),
                ('minmax', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('place_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='whens', to='places.Place')),
            ],
            options={
                'db_table': 'place_when',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_id', models.CharField(max_length=30, unique=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('citation', models.CharField(blank=True, max_length=500, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sources',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='placename',
            name='name_src',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Source'),
        ),
        migrations.AddField(
            model_name='placename',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='places.Place'),
        ),
        migrations.AddField(
            model_name='placegeom',
            name='geom_src',
            field=models.ForeignKey(db_column='geom_src', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Source', to_field='src_id'),
        ),
        migrations.AddField(
            model_name='placegeom',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='geoms', to='places.Place'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['src_id', 'dataset'], name='places_src_id_486bf2_idx'),
        ),
    ]
