# Generated by Django 4.1.7 on 2023-04-09 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0003_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placewhen',
            name='place',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='whens', to='places.place'),
        ),
        migrations.AddField(
            model_name='placetype',
            name='place',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='places.place'),
        ),
        migrations.AddField(
            model_name='placerelated',
            name='place',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='places.place'),
        ),
        migrations.AddField(
            model_name='placename',
            name='name_src',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.source'),
        ),
        migrations.AddField(
            model_name='placename',
            name='place',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='places.place'),
        ),
        migrations.AddField(
            model_name='placelink',
            name='place',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='places.place'),
        ),
        migrations.AddField(
            model_name='placegeom',
            name='geom_src',
            field=models.ForeignKey(db_column='geom_src', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.source', to_field='src_id'),
        ),
        migrations.AddField(
            model_name='placegeom',
            name='place',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='geoms', to='places.place'),
        ),
        migrations.AddField(
            model_name='placedescription',
            name='place',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='places.place'),
        ),
        migrations.AddField(
            model_name='placedepiction',
            name='place',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='depictions', to='places.place'),
        ),
        migrations.AddField(
            model_name='place',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='places', to='datasets.dataset', to_field='label'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['src_id', 'dataset'], name='places_src_id_486bf2_idx'),
        ),
    ]
