# Generated by Django 2.1.7 on 2019-04-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelink',
            name='black_parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
