# Generated by Django 2.1.7 on 2019-06-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190420_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='src_id',
            field=models.CharField(max_length=2044),
        ),
    ]
