# Generated by Django 2.2.4 on 2019-08-29 18:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20190630_1546'),
    ]

    operations = [

    ]
