# Generated by Django 2.2.4 on 2019-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20190829_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedepiction',
            name='src_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='placedescription',
            name='src_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='placegeom',
            name='src_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='placelink',
            name='src_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='placename',
            name='src_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='placerelated',
            name='src_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='src_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='placewhen',
            name='src_id',
            field=models.CharField(default='', max_length=100),
        )
    ]
