# Generated by Django 2.2.10 on 2020-04-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_indexed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placegeom',
            old_name='place_id',
            new_name='place',
        ),
    ]
