# Generated by Django 2.2.10 on 2020-04-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200422_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedepiction',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='placedescription',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='placelink',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='placename',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='placerelated',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='placetype',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='placewhen',
            old_name='place_id',
            new_name='place',
        ),
    ]
