# Generated by Django 2.2.10 on 2020-04-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_placetype_aat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='fclass',
            field=models.CharField(choices=[('A', 'Administrative divisions'), ('H', 'Hydrological features'), ('L', 'Landscape, regions'), ('P', 'Populated places (settlements)'), ('R', 'Roads, routes, transportation'), ('S', 'Sites (various)'), ('T', 'Topographical features'), ('U', 'Undersea features'), ('V', 'Vegetation landcover')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
