# Generated by Django 2.2.10 on 2020-05-02 22:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_placetype_fclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='fclasses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('A', 'Administrative divisions'), ('H', 'Hydrological features'), ('L', 'Landscape, regions'), ('P', 'Populated places (settlements)'), ('R', 'Roads, routes, transportation'), ('S', 'Sites (various)'), ('T', 'Topographical features'), ('U', 'Undersea features'), ('V', 'Vegetation landcover')], max_length=1), blank=True, null=True, size=None),
        ),
    ]
