# Generated by Django 2.2.10 on 2020-05-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_place_fclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aat_id', models.IntegerField(unique=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(max_length=100)),
                ('term_full', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=3000)),
                ('fclass', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'types',
                'managed': True,
            },
        ),
    ]
