# Generated by Django 2.2.10 on 2020-05-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='fclass',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
