# Generated by Django 2.2.20 on 2021-04-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20210424_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='review_tgn',
        ),
        migrations.RemoveField(
            model_name='place',
            name='review_wd',
        ),
        migrations.RemoveField(
            model_name='place',
            name='review_whg',
        ),
    ]
