# Generated by Django 2.2.20 on 2021-04-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_auto_20210424_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='review_tgn',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (-1, 'Deferred')], default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='review_wd',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (-1, 'Deferred')], default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='review_whg',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (-1, 'Deferred')], default=0),
        ),
    ]
