# Generated by Django 2.2.20 on 2021-04-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20210424_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='review_tgn',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (2, 'Deferred')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='review_wd',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (2, 'Deferred')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='review_whg',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (2, 'Deferred')], default=0, null=True),
        ),
    ]
