# Generated by Django 2.2.20 on 2021-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20210529_1903'),
        ('places', '0018_auto_20210426_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='collections',
            field=models.ManyToManyField(to='collection.Collection'),
        ),
    ]
