# Generated by Django 2.2.20 on 2021-05-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_auto_20210426_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='review_tgn',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (2, 'Deferred')], null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='review_wd',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (2, 'Deferred')], null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='review_whg',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (2, 'Deferred')], null=True),
        ),
    ]
