# Generated by Django 2.2.4 on 2019-12-06 10:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='geojson',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('ccodes', 'Country codes'), ('drawn', 'User drawn'), ('copied', 'CopyPasted GeoJSON'), ('predefined', 'World Regions'), ('search', 'Region/Polity record')], max_length=20),
        ),
    ]
