# Generated by Django 4.1.7 on 2023-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('search', 'Region/Polity record'), ('drawn', 'User drawn'), ('copied', 'CopyPasted GeoJSON'), ('ccodes', 'Country codes'), ('predefined', 'World Regions')], max_length=20),
        ),
    ]
