# Generated by Django 2.2.13 on 2020-12-17 23:05

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_auto_20200310_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgnid', models.IntegerField(blank=True, null=True)),
                ('tgnlabel', models.CharField(blank=True, max_length=255, null=True)),
                ('iso', models.CharField(max_length=2)),
                ('gnlabel', models.CharField(max_length=255)),
                ('geonameid', models.IntegerField()),
                ('un', models.CharField(blank=True, max_length=3, null=True)),
                ('variants', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
