# Generated by Django 2.2.13 on 2021-03-30 18:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0014_auto_20200521_1408'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0025_auto_20210330_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2044)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='CollectionPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='coll_places', to='collection.Collection')),
                ('place', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.Place')),
            ],
            options={
                'db_table': 'collection_place',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CollectionDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collection_datasets', to='collection.Collection')),
                ('dataset', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_collections', to='datasets.Dataset')),
            ],
            options={
                'db_table': 'collection_dataset',
                'managed': True,
            },
        ),
    ]
