# Generated by Django 2.2.20 on 2021-06-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='tags',
            new_name='keywords',
        ),
    ]
