# Generated by Django 2.2.13 on 2021-03-31 01:14

import collection.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_file',
            field=models.FileField(default='', upload_to=collection.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
