# Generated by Django 4.1.7 on 2023-04-09 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0002_initial'),
        ('collection', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionuser',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='coll_collab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionlink',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='collection.collection'),
        ),
        migrations.AddField(
            model_name='collectiongroupuser',
            name='collectiongroup',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='collection.collectiongroup'),
        ),
        migrations.AddField(
            model_name='collectiongroupuser',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='collections',
            field=models.ManyToManyField(blank=True, to='collection.collection'),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='datasets',
            field=models.ManyToManyField(blank=True, to='datasets.dataset'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='places',
            field=models.ManyToManyField(blank=True, to='places.place'),
        ),
    ]
