# Generated by Django 4.1.7 on 2023-04-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='gallery_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='type',
            field=models.CharField(choices=[('class', 'Class'), ('workshop', 'Workshop')], default='class', max_length=8),
        ),
    ]
