# Generated by Django 2.2.20 on 2021-05-29 19:03

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20210331_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_file',
            #field=models.FileField(null=True, upload_to=collection.models.user_directory_path),
            field=models.FileField(null=True, upload_to=collection.models.coll_image_path),
        ),
    ]
