# Generated by Django 4.1.7 on 2023-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collectiongroup_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
