# Generated by Django 4.1.7 on 2023-04-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collection_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='group',
        ),
    ]
