# Generated by Django 2.2.20 on 2021-06-04 18:46

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collection_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to=collection.models.user_directory_path),
        ),
    ]
