# Generated by Django 2.2.20 on 2021-06-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20210604_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='featured',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
