# Generated by Django 4.1.7 on 2023-04-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_collection_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group', to='collection.collectiongroup'),
        ),
    ]
