# Generated by Django 4.1.7 on 2023-04-29 09:17

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_collection_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=collection.models.collection_path),
        ),
    ]
