# Generated by Django 2.2.20 on 2021-06-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_collection_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='collections/'),
        ),
    ]
