# Generated by Django 4.1.7 on 2023-04-30 16:38

import collection.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_collectiongroup_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=collection.models.collectiongroup_path),
        ),
        migrations.AlterField(
            model_name='collectionlink',
            name='link_type',
            field=models.CharField(choices=[('page', "<i title class='fas fa-window-maximize'></i>"), ('image', '<img src="/static/images/noun-photo.svg" width="16"/>'), ('pdf', "<i title class='far fa-file-pdf linky'></i>")], default='page', max_length=10),
        ),
        migrations.CreateModel(
            name='CollectionGroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('uri', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('link_type', models.CharField(choices=[('page', "<i title class='fas fa-window-maximize'></i>"), ('image', '<img src="/static/images/noun-photo.svg" width="16"/>'), ('pdf', "<i title class='far fa-file-pdf linky'></i>")], default='page', max_length=10)),
                ('license', models.CharField(blank=True, max_length=64, null=True)),
                ('collection_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='collection.collectiongroup')),
            ],
            options={
                'db_table': 'collection_group_link',
                'managed': True,
            },
        ),
    ]
