# Generated by Django 4.1.7 on 2023-05-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
        ('collection', '0010_alter_collectiongrouplink_link_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
        migrations.AlterField(
            model_name='collectionlink',
            name='link_type',
            field=models.CharField(choices=[('webpage', "<i title class='fas fa-window-maximize'></i>"), ('image', '<img src="/static/images/noun-photo.svg" width="16"/>'), ('document', "<i title class='far fa-file-pdf linky'></i>")], default='webpage', max_length=10),
        ),
        migrations.DeleteModel(
            name='CollectionGroupLink',
        ),
    ]
