# Generated by Django 4.1.7 on 2023-05-06 10:46
# modified per https://stackoverflow.com/questions/26927705/django-migration-error-you-cannot-alter-to-or-from-m2m-fields-or-add-or-remove

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
        ('collection', '0011_collplace_alter_collectionlink_link_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='places'
        ),
        migrations.AddField(
            model_name='collection',
            name='places',
            field=models.ManyToManyField(blank=True, through='collection.CollPlace', to='places.place'),
        ),
        # migrations.AlterField(
        #     model_name='collection',
        #     name='places',
        #     field=models.ManyToManyField(blank=True, through='collection.CollPlace', to='places.place'),
        # ),
    ]
