# Generated by Django 4.1.7 on 2023-05-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
        ('collection', '0012_alter_collection_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collplace',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annos', to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='collplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annos', to='places.place'),
        ),
    ]
