# Generated by Django 4.1.7 on 2023-05-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_alter_collplace_collection_alter_collplace_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='omitted',
        ),
        migrations.AddField(
            model_name='collection',
            name='nominate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
