# Generated by Django 4.1.7 on 2023-05-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_remove_collection_omitted_collection_nominate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('ready', 'Ready'), ('demo', 'Demo'), ('sandbox', 'Sandbox'), ('group', 'Group')], default='sandbox', max_length=12, null=True),
        ),
    ]
