# Generated by Django 4.1.7 on 2023-05-24 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0015_alter_collection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='submitted',
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(blank=True, choices=[('sandbox', 'Sandbox'), ('demo', 'Demo'), ('group', 'Group'), ('reviewed', 'Reviewed'), ('nominated', 'Nominated'), ('published', 'Published')], default='sandbox', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='collectionlink',
            name='link_type',
            field=models.CharField(choices=[('webpage', "<i class='fas fa-window-maximize'></i>"), ('image', '<img src="/static/images/noun-photo.svg" width="16"/>'), ('document', "<i class='far fa-file-pdf linky'></i>")], default='webpage', max_length=10),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='collection',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
