# Generated by Django 4.1.7 on 2023-04-09 14:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import traces.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=255)),
                ('collection', models.ForeignKey(db_column='collection', on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='collection.collection')),
            ],
            options={
                'db_table': 'trace_relations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TraceAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_id', models.CharField(blank=True, max_length=2044, null=True)),
                ('note', models.CharField(blank=True, max_length=2044, null=True)),
                ('image_file', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[800, 600], upload_to=traces.models.collection_path)),
                ('relation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('start', models.CharField(blank=True, max_length=11, null=True)),
                ('end', models.CharField(blank=True, max_length=11, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('anno_type', models.CharField(blank=True, default='place', max_length=20, null=True)),
                ('motivation', models.CharField(default='locating', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.BooleanField(default=False)),
                ('when', models.JSONField(blank=True, null=True)),
                ('collection', models.ForeignKey(db_column='collection', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='collection.collection')),
            ],
            options={
                'db_table': 'trace_annotations',
                'managed': True,
            },
        ),
    ]
