# Generated by Django 4.1.7 on 2023-05-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_alter_collection_places'),
        ('places', '0002_initial'),
        ('traces', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceannotation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='traceannotation',
            name='collection',
            field=models.ForeignKey(db_column='collection', on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='traceannotation',
            name='place',
            field=models.ForeignKey(db_column='place', on_delete=django.db.models.deletion.CASCADE, related_name='place', to='places.place'),
        ),
    ]
