# Generated by Django 2.2.4 on 2019-12-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='unspecified', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group or project team')], default='individual', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='web_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
