# Generated by Django 2.1.7 on 2019-04-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
