# Generated by Django 4.1.7 on 2023-05-01 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_alter_collectiongrouplink_link_type_and_more'),
        ('places', '0002_initial'),
        ('traces', '0002_initial'),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('link_type', models.CharField(choices=[('webpage', "<i title class='fas fa-window-maximize'></i>"), ('image', '<img src="/static/images/noun-photo.svg" width="16"/>'), ('pdf', "<i title class='far fa-file-pdf linky'></i>")], default='webpage', max_length=10)),
                ('license', models.CharField(blank=True, max_length=64, null=True)),
                ('collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='collection.collection')),
                ('collection_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='collection.collectiongroup')),
                ('place', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='places.place')),
                ('trace_annotation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='traces.traceannotation')),
            ],
            options={
                'db_table': 'links',
                'managed': True,
            },
        ),
    ]
