# Generated by Django 2.1.7 on 2019-04-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190404_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='whg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
