# Generated by Django 2.1.7 on 2019-04-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190404_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='whg_id',
            new_name='place_id',
        ),
    ]
