# Generated by Django 4.1.7 on 2023-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('webpage', "<i title class='fas fa-window-maximize'></i>"), ('image', '<img src="/static/images/noun-photo.svg" width="16"/>'), ('document', "<i title class='far fa-file-pdf linky'></i>")], default='webpage', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='uri',
            field=models.URLField(),
        ),
    ]
