# Generated by Django 2.1.7 on 2019-04-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190404_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='place_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='whg_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
