# Generated by Django 2.1.7 on 2019-04-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190405_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='whg_id',
            new_name='place_id',
        ),
    ]
