# Generated by Django 2.1.7 on 2019-04-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190405_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
