# Generated by Django 2.2.10 on 2020-03-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='created_date',
            new_name='timestamp',
        ),
    ]
