# Generated by Django 2.2.10 on 2020-03-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200310_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
