# Generated by Django 4.1.7 on 2023-04-09 14:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pub_date', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Lesson plan', 'Lesson plan'), ('Syllabus', 'Syllabus'), ('Other', 'Other')], max_length=12)),
                ('description', models.TextField(max_length=2044)),
                ('subjects', models.CharField(max_length=2044)),
                ('gradelevels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=24), size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), size=None)),
                ('authors', models.CharField(max_length=500)),
                ('contact', models.CharField(blank=True, max_length=500, null=True)),
                ('webpage', models.URLField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('featured', models.IntegerField(blank=True, null=True)),
                ('regions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(72, 'Antarctica'), (73, 'Asiatic Russia'), (74, 'Australia/New Zealand'), (75, 'Caribbean'), (76, 'Central America'), (77, 'Central Asia'), (78, 'Eastern Africa'), (79, 'Eastern Asia'), (80, 'Eastern Europe'), (81, 'European Russia'), (82, 'Melanesia'), (83, 'Micronesia'), (84, 'Middle Africa'), (85, 'Northern Africa'), (86, 'Northern America'), (87, 'Northern Europe'), (88, 'Polynesia'), (89, 'South America'), (90, 'Southeastern Asia'), (91, 'Southern Africa'), (92, 'Southern Asia'), (93, 'Southern Europe'), (94, 'Western Africa'), (95, 'Western Asia'), (96, 'Western Europe'), (99, 'Global')], max_length=77, null=True)),
                ('status', models.CharField(blank=True, choices=[('uploaded', 'File uploaded'), ('published', 'Published')], default='uploaded', max_length=12, null=True)),
            ],
            options={
                'db_table': 'resources',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=resources.models.resource_file_path)),
                ('resource', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
            options={
                'db_table': 'resource_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resources.models.resource_file_path)),
                ('filetype', models.CharField(choices=[('primary', 'Primary file'), ('supporting', 'Supporting file')], default='primary', max_length=12)),
                ('resource', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
            options={
                'db_table': 'resource_file',
                'managed': True,
            },
        ),
    ]
